# Python Basic interview Question

## 7. Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.
* Suppose the following inputs are given to the program: 3, 5
* Then, the output of the program should be: [[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]


In [3]:
import numpy as np

In [12]:
lis=[]
row=int(input("enter Number of Row :"))
col=int(input("enter the Number of Columns :"))
for i in range(row):
    for j in range(col):
        lis.append(i*j)
x=np.array(lis).reshape(row,col)
print(x)

enter Number of Row :5
enter the Number of Columns :8
[[ 0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7]
 [ 0  2  4  6  8 10 12 14]
 [ 0  3  6  9 12 15 18 21]
 [ 0  4  8 12 16 20 24 28]]


In [5]:
l=[]
row=int(input("enter number of raw :-"))
col=int(input("enter number of columns :-"))
import numpy as np
for i in range(row):
    for j in range(col):
        l.append(i*j)
                
x=np.array(l).reshape(3,5)
print(x)

enter number of raw :-3
enter number of columns :-5
[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]


In [7]:
row_num = int(input("Input number of rows: "))
col_num = int(input("Input number of columns: "))
multi_list = [[0 for col in range(col_num)] for row in range(row_num)]

for row in range(row_num):
    for col in range(col_num):
        multi_list[row][col]= row*col

print(multi_list)

Input number of rows: 3
Input number of columns: 5
[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]


 # Done -----------